### ISSUE TITLE
expect(...).toEqual(...) hangs if not equal

### ISSUE THREAD

**Issue by davidvuong** [mjackson/expect#77]
This happens when I'm using `expect` with `redux-mock-store` and `redux-thunk` so I'm not sure if this is something you guys can fix but I'll report it anyway. Feel free to close this issue if it can't be fixed here.

Here's an example: https://github.com/davidvuong/node-react-bp/blob/master/test/actions/ColoredSquareActionCreators-test.js#L17-L40

If you replace the body:

```js
store.dispatch(actions.fetchColor()).then(() => {
  expect(store.getActions()).toEqual(expectedActions);
  done();
});
```

with

```js
store.dispatch(actions.fetchColor()).then(() => {
  expect({}).toEqual([]);
  done();
});
```

I get an error saying that `done` is never called because the statement above it hangs (not sure for how longer but longer than the default timeout):

```
  1) ColoredSquareActionCreators should create async action when fetching color:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Any ideas why?

**Comment by rstacruz** [comment]
Are you using mocha?

Are you using `it('works', function (next) {` with a `next`?

**Comment by rstacruz** [comment]
> ```js
store.dispatch(actions.fetchColor()).then(() => {
  expect({}).toEqual([]);
  done();
});
```

don't use `then()` here. redux's `dispatch()` doesn't return a promise, afaik.

**Comment by vvo** [comment]
Are you using mocha? Because then you can just return the the promise.

**Comment by mjackson** [comment]
This definitely isn't our problem. We `throw` immediately.

**Comment by davidvuong** [comment]
Thanks for the responses but I'm still not quite sure how to fix this.

@rstacruz The `dispatch` method is from `redux-mock-store` (https://github.com/arnaudbenard/redux-mock-store/blob/master/src/index.js#L20-L24). The promise is from an async action creator. I'm certain the `.then` callback is called. If I do this:

```js
store.dispatch(actions.fetchColor()).then(() => {
  console.log('hello');
  expect([]).toEqual({});
  console.log('world');
  done();
});
```

It prints out "hello" but not "world".

@vvo Yep, I'm using Mocha but what promise are you referring to? The only promise I see is the one returned from my `fetchColor` action creator. If I return that promise how can I make an assertion?

@mjackson You're absolutely right. If I change the body to be:

```js
store.dispatch(actions.fetchColor()).then(() => {
  try {
    expect([]).toEqual({});
  } catch(e) {
    console.log(e);
  }
  done();
});
```

`done()` gets invoked and I get this friendly error message:

```
{ [Error: Expected [] to equal {}] showDiff: true, actual: [], expected: {} }
```

Do you think this might be a problem with Mocha? Am I expected to always have the `expect` within a try catch block? Is there a reason why the exception it's being caught and handled somewhere higher up?

**Comment by ngthorg** [comment]
```
store.dispatch(actions.fetchColor()).then(() => {
  expect(store.getActions()).toEqual(expectedActions);
}).then(done).catch(done);
```

**Comment by elad-maimon** [comment]
I have exactly the same issue.

@mjackson you said it's definitely not your problem because you `throw` immediately - I think this is the problem because it never gets to the `done()` call after it.
When I revert back to use jasmine expect it never throws, so this two behaves differently...

I've also added `.catch` as @ngthorg suggested and it gets into it but it's not a solution IMHO.

Please try to address this issue since it's really a problem to receive incorrect error messages on test failures.

**Comment by ljharb** [comment]
@elad-maimon that's the exact solution for promises. You could do `.then(done, done)` as well, but in every case you have to handle the error inside the promise.

**Comment by wuct** [comment]
@elad-maimon What @ngthorg suggested was actually came from [the doc](https://github.com/arnaudbenard/redux-mock-store/commit/483da06337f64abf242fc7b13c0d1651753c8d22) of `redux-mock-store`. However, `mocha` accepts a promise returned from `it`, so they remove `.then(done).catch(done)` from the doc.
